# Copyright 2020-present Open Networking Foundation
# Copyright 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
[ req ]
default_bits           = 4096
distinguished_name     = stratum-ca
prompt                 = no
x509_extensions        = ca_ext

[ stratum-ca ]
C                      = US
ST                     = CA
L                      = Menlo Park
O                      = Open Networking Foundation
OU                     = Stratum
CN                     = Stratum CA

[ ca_ext ]
basicConstraints       = critical, CA:true
keyUsage               = critical, digitalSignature, keyCertSign, cRLSign
subjectKeyIdentifier   = hash
