# Copyright 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
[ req ]
default_bits           = 4096
distinguished_name     = stratum
prompt                 = no
req_extensions         = server_ext

[ stratum ]
C                      = US
ST                     = CA
L                      = Menlo Park
O                      = Open Networking Foundation
OU                     = Stratum
CN                     = ${COMMON_NAME}

[ server_ext ]
basicConstraints       = CA:false
keyUsage               = critical, digitalSignature, keyEncipherment
extendedKeyUsage       = serverAuth
subjectAltName         = @alt_names

[ alt_names ]
DNS.1                  = ${COMMON_NAME}
