# Copyright 2020-present Open Networking Foundation
# Copyright 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
[ req ]
default_bits           = 4096
distinguished_name     = grpc-client
prompt                 = no
req_extensions         = client_ext

[ grpc-client ]
C                      = US
ST                     = CA
L                      = Menlo Park
O                      = Open Networking Foundation
OU                     = Stratum
CN                     = Stratum client certificate

[ client_ext ]
basicConstraints       = CA:false
keyUsage               = critical, digitalSignature, keyEncipherment
extendedKeyUsage       = clientAuth
